name: CD - Spring Boot

on:
  push:
    branches:
      - main
      - danny-docker

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-to-registry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build the JAR
        working-directory: ./carnet
        run: mvn clean package

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        working-directory: ./carnet
        run: docker build -t ghcr.io/${{ github.repository }}/carnet:latest .

      - name: Push the Docker image
        working-directory: ./carnet
        run: docker push ghcr.io/${{ github.repository }}/carnet:latest
