name: CI - Spring Boot

on:
  push:
    branches:
      - main
      - danny
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests
        working-directory: ./carnet
        run: mvn clean test
