name: CI - Spring Boot

on:
  push:
    branches:
      - main
      - danny
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Display environment information
        run: |
          java -version
          mvn -version

      - name: Run tests
        working-directory: ./carnet
        run: mvn -X test

      - name: Upload surefire reports
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: surefire-reports
          path: carnet/target/surefire-reports
